server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/academic_affairs_management_system_db?serverTimezone=UTC
      username: root
      password: root
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis-plus:
  global-config:
    db-config:
      id-type: input

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
